### ISSUE TITLE
Troubleshooting Serial Port Access in Aduno IDE

### ISSUE THREAD

**Issue by nulLeeKH** [UNIST-STEM/2020#2]
*문제*
- 아두이노 IDE에서 시리얼 포트에 접근할 수 없음

*해결*
1. [sudo chmod a+rw /dev/ttyACM0] 명령어를 이용해 시리얼 포트에 대한 접근권한 부여

**Comment by Esthesia** [comment]
website에서 권한부여 설정 매뉴얼에 추가했습니다.

**Comment by nulLeeKH** [comment]
감사합니다 :D
